### ISSUE TITLE
0.8 deployment checklist

### ISSUE THREAD

**Issue by izqui** [aragon/deployments#114]
## aragonOS

- [x] Merge https://github.com/aragon/aragonOS/pull/551 (@izqui)
- [x] ~External code review for https://github.com/aragon/aragonOS/pull/551~ (won't do)
- [x] Release aragonOS 4.3 (@facuspagnuolo)
- [x] Deploy `DAOFactory` (@facuspagnuolo)
- [x] Develop proxy versioning oracle (@izqui): https://github.com/aragonone/version-oracle/pull/1
~~- [ ] Deploy proxy versioning oracle (@izqui)~~
- [x] Verify aragonOS mainnet contracts in Etherscan (@izqui)

## Templates

- [x] Finish review and merge https://github.com/aragon/dao-templates/pull/150 (@sohkai)
- [x] Staging: publish templates https://github.com/aragon/dao-templates/pull/157 (@facuspagnuolo)
- [x] Rinkeby: publish templates (@izqui)
- [x] Mainnet: publish templates (@izqui)

## Client

- [x] Staging: initial release (@sohkai)
- [x] Staging: release candidate (@sohkai)
- [x] Rinkeby: major (?) release (@izqui)
- [x] Mainnet: major (?) release (@izqui)

### Agent

- [x] Staging: major release (@sohkai)
- [x] End to end test on staging (@sohkai, @facuspagnuolo, @izqui)
- [x] Rinkeby: minor release (@izqui)
- [x] Mainnet: major release (@izqui)

### Finance, Voting, TM

- [x] Staging: minor releases (@sohkai)
- [x] Rinkeby: minor releases (@izqui)
- [x] Rinkeby: minor releases (@izqui)
